name: RocketModFix.UnityEngine.Redist

on:
  push:
    branches: [ master ]
    paths:
      - 'redist/**'

jobs:
  build:
    name: "RocketModFix.UnityEngine.Redist Pack"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: 8.x
    - uses: nuget/setup-nuget@v2
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget-version: '5.x'
    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: redist/RocketModFix.UnityEngine.Redist.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true